version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: typescript
        update-types: [version-update:semver-major]
      - dependency-name: '@babel/core'
        update-types: [version-update:semver-major]
    groups:
      expo:
        patterns:
          - expo
          - expo-*
          - '@expo/*'
          - react
          - react-dom
          - react-native
          - react-native-*
          - '@react-native*/*'

        update-types: [minor, patch]
        exclude-patterns:
          - react-native-reanimated
          - react-native-worklets
      development:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ['*']
